services:
  eventlib-server:
    build:
      context: .
      dockerfile: ./eventlibserver/Dockerfile
    container_name: eventlib-server
    ports:
      - "8080:8080" # API port
      - "9090:9090" # Metrics port
    environment:
      - LOG_LEVEL=info
    command:
      - "-addr=:8080"
      - "-metrics-addr=:9090"
      - "-queue-size=10000"
      - "-name=DockerEventProcessor"
    restart: unless-stopped
    networks:
      - eventlib-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/api/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  eventlib-network:
    driver: bridge

volumes:
  prometheus-data:
